services:
    #VueJS Service
    frontend:
      build:
        context: ./frontend/ 
      container_name: vue_js
      ports:
        - "8080:8080"
      volumes:
          - "/app/node_modules" 
          - "./frontend:/app"
      networks:
        - app-network

    #Lumen Service
    backend:
      build:
        context: ./backend/ 
      container_name: lumen
      restart: unless-stopped
      environment:
        SERVICE_NAME: lumen
        SERVICE_TAGS: dev
      working_dir: /var/www/html/
      volumes:
        - ./backend:/var/www/html
      networks:
        - app-network
        - db

    #Nginx Service
    webserver:
      image: nginx:alpine
      container_name: webserver_lumen
      restart: unless-stopped
      tty: true
      ports:
        - "8081:8081"
      volumes:
        - ./backend:/var/www/html/
        - ./nginx/conf.d/:/etc/nginx/conf.d/
      networks:
        - app-network

    #MySQL Service
    database:
      image: mysql:8.0
      # command: --default-authentication-plugin=mysql_native_password
      platform: linux/amd64
      container_name: database
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      volumes:
        - ./local-data/db:/var/lib/mysql
      ports:
        - 3306:3306
      networks:
        - db

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: unless-stopped
      environment:
        PMA_HOST: database
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      depends_on:
        - database
      ports:
        - 8443:80
      networks:
        - db

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
  db: